ProjectKiwi/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^short/', include('urlshortener.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^$', include('hub.urls')),
]

hub/urls.py
from django.conf.urls import url

from . import views

app_name = 'hub'
urlpatterns = [
    #ex: mwaboff.com
        url(r'^', views.index, name='index'),
]

urlshortener/urls.py
from django.conf.urls import url

from . import views

app_name = 'short'
urlpatterns = [
    #ex: /short/
        url(r'^$', views.index, name='index'),
    #ex: /short/create
        url(r'^api/create/$', views.create, name='create'),
    #ex: /short/i32s5/info
        url(r'^(?P<short_url>\w+)/info/$', views.info_viewer, name='info_viewer'),
    #ex: /short/i32s5
        url(r'^(?P<short_url>\w+)/$', views.redirector, name='redirect'),
]

hub/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.utils import timezone

import datetime
# Create your models here.

class Project(models.Model):
    name = models.CharField(max_length=100, unique=True)
    short_desc = models.CharField('Short Description', max_length=140)
    long_desc = models.TextField('Long Description')
    tech_used = models.CharField('Technology Used', max_length=140, default='')
    git_link = models.URLField('Github URL', blank=True)
    live_link = models.URLField('Live URL', blank=True)
    img_link = models.URLField('Image Link', blank=True)
    order_int = models.IntegerField('Order (lower is ranked higher)', default=0)

    def __str__(self):
        return self.name

urlshortener/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.utils import timezone

import datetime
# Create your models here.

class URL(models.Model):
    orig_url = models.URLField('original URL')
    short_url = models.CharField('shortened URL', max_length=100, unique=True)
    creation_date = models.DateTimeField('date created', default=timezone.now)
    views = models.IntegerField(default=0)

    def __str__(self):
        return "boff.io/" + self.short_url

hub/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, get_object_or_404

# Create your views here.

from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.urls import reverse
from .models import Project


# Create your views here.

def index(request):
    projects = Project.objects.order_by('order_int')
    return render(request, 'hub/index.html', {'portfolio': projects})

urlshortener/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, get_object_or_404

from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.urls import reverse
from django.views import generic
from django.utils import timezone

from .models import URL
from .scripts.url_helper import create_url

# Create your views here.

def index(request):
    return render(request, 'urlshortener/index.html')

def redirector(request, short_url):
    found_URL_obj = get_object_or_404(URL, short_url=short_url)
    found_URL_obj.views += 1
    found_URL_obj.save()
    long_url = found_URL_obj.orig_url
    return HttpResponseRedirect(long_url)
    #return HttpResponse("You're on the redirect page for id=%s. The long_url = %s" % (short_url, long_url))

def info_viewer(request, short_url):
    found_URL_obj = get_object_or_404(URL, short_url=short_url)
    url_info = {
        'short_addr': found_URL_obj,
        'short_url': short_url,
        'long_url': found_URL_obj.orig_url,
        'views': found_URL_obj.views,
        'create_date': found_URL_obj.creation_date
    }
    return render(request, 'urlshortener/info.html', url_info)
    #return HttpResponse("You're on the info page for id=%s" % short_url)

def create(request):
    long_url = request.POST['long_url'].strip()
    short_url = request.POST['short_url'].strip()
    
    new_url = create_url(long_url, short_url)
    if new_url[0] == -1:
        error_info = {
            'success': -1,
            'message': "You dun goofed up. Make sure you put a valid URL in!"
        }
        return JsonResponse(error_info)
    elif new_url[0] == -2:
        error_info = {
            'success': 0,
            'message': "This short URL has already been taken, try another or keep it blank."
        }
        return JsonResponse(error_info)
    else:
        url_info = {
            'success': new_url[0],
            'short_addr': str(new_url[1]),
            'short_url': new_url[1].short_url,
            'long_url': new_url[1].orig_url,
        }

        return JsonResponse(url_info)

hub/templates/hub/hub_base.html
{% extends 'global_base.html' %}
{% load staticfiles %}

{% block title %}Michael Aboff - Software Developer and IT Professional{% endblock %}

{% block more_header %}
<link rel="stylesheet" type="text/css" href="{% static 'hub/css/hub_app.css' %}" />
<script type="text/javascript" src="{% static 'hub/js/main.js' %}"></script>

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">

<script src="https://use.fontawesome.com/93d91f2111.js"></script>
{% endblock %}

{% block boff-links %}
<!--<a href="#portfolio" class="boff-link">Portfolio</a>-->
{% endblock %}

hub/templates/hub/index.html
{% extends 'hub/hub_base.html' %}
{% load staticfiles %}

{% block more_header %}
{{ block.super }}
<link rel="stylesheet" type="text/css" href="{% static 'hub/css/index.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'global/css/jquery.fullPage.css' %}" />
<script type="text/javascript" src="{% static 'global/js/jquery.fullPage.min.js' %}"></script>
{% endblock %}

{% block logo %}
<a href="#intro" id="logo">MWA</a>
{% endblock %}

{% block body %}
<div id='fullpage'>
    <div class='section' id='section-intro' data-anchor='intro'>
        <div id='intro-text'>Hi! I'm Michael</div>
        <div class='intro-about'>I love making this crazy world just a little bit easier, one project at a time.</div>
        <div class='contact-container'>
            <a href='mailto:mwaboff@gmail.com' class='contact-link .contact-ico' title='Mail me!'>
                <i class="fa fa-envelope"></i>
            </a>
            <a href='https://www.linkedin.com/in/mwaboff/' class='contact-link .contact-ico' title='Linkin'>
                <i class="fa fa-linkedin"></i>
            </a>
            <a href='http://www.github.com/mwaboff' class='contact-link .contact-ico' title='Github'>
                <i class="fa fa-github"></i>
            </a>
            <a href='https://www.dropbox.com/s/f94nu1l5e22f9fg/michael_aboff_v2.pdf?dl=0' class='contact-link .contact-txt' title='Resume'>
                <i class="fa fa-file-pdf-o"></i>
            </a>
        </div>
    </div>
    {% include 'hub/portfolio_entry.html' with projects=portfolio %}
</div>
{% endblock %}

hub/templates/hub/portfolio.html
<div class='content-container'>
    <div class='project-content'>
        <div class='my-projects'>
            <div class='project' id='project-1'>
                <div class='project-title'>
                    boff.io
                </div>
                <div class='project-desc'>
                    An easy to use URL shortener built with python, JavaScript, Django, and a sprinkling of love.
                </div>
            </div>
            <div class='project' id='project-2'>
                <div class='project-title'>
                    MonkeyScripts
                </div>
                <div class='project-desc'>
                    A modern userscript hosting and discovery site. Designed with Rails, JavaScript, and Backbone.js
                </div>
            </div>
            <div class='project' id='project-2'>
                <div class='project-title'>
                    HF Enhancement Suite
                </div>
                <div class='project-desc'>
                    A massive browser script enjoyed by over 4000 users. Earned over $3000!
                </div>
            </div>
            <div class='project' id='project-1'>
                <div class='project-title'>
                    Craybot
                </div>
                <div class='project-desc'>
                    A sassy, python IRC bot focused on administration, designed for extreme customization.
                </div>
            </div>
            <div class='project' id='project-2'>
                <div class='project-title'>
                    Super Awesome File Deleter
                </div>
                <div class='project-desc'>
                    A python script that quickly deletes files and folders based off of user made config files.
                </div>
            </div>
            <div class='project' id='project-2'>
                <div class='project-title'>
                    Sweet Proxy Scraper
                </div>
                <div class='project-desc'>
                    Scrape working HTTP and Socks proxies from all over the web! Built with python.
                </div>
            </div>
        </div>
    </div>
</div>

<!--<div class='section fp-auto-height' id='section-portfolio' style='background-color:red'>
        <div class='content-container'>
            <div class='content'>
                <div class='project-title'>
                    HF Enhancement Suite
                </div>
                <div class='project-info'>
                    <div class='info-desc'>
                        boff.io is designed to be the simplest, concise, and beautiful URL shortener available. Users can customize links and track how many times it has been used.
                    </div>
                    <div class='project-img'></div>
                    <div class='info-tech'>
                        <b>Tech:</b> Python, Django, jQuery
                    </div>
                    <ul class='info-links'>
                        <li>Live</li>
                        <li>Github</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>-->

hub/templates/hub/portfolio_entry.html
<div class='section fp-auto-height section-portfolio' data-anchor="portfolio">
    <div class='portfolio-container'>


        {% for project in projects %}
        <div class='portfolio row justify-content-center'>

            <div class='project-short-info row justify-content-center'>
                <div class='project-img col-md-3 col-sm-2'>
                    <img class='mx-auto d-block' src='{{ project.img_link }}' />
                </div>
                <div class='col-md-1 col-sm-1'></div>

                <div class='project col-md-5 col-sm-5' id='project-{{ forloop.counter }}' >
                    <div class='project-title'>
                        {{ project.name }}
                    </div>
                    <div class='project-info'>
                        <div class='info-desc'>
                            {{ project.short_desc }}
                        </div>
                        <div class='info-tech'>
                            <b>Tech:</b> {{ project.tech_used }}
                        </div>
                        <div class='info-link-container'>
                            {% if project.live_link %}
                            <a href='{{ project.live_link }}' class='info-link info-live' target='_blank'>Live</a>
                            {% endif %}
                            {% if project.git_link %}
                            <a href='{{ project.git_link }}' class='info-link' target='_blank'>Github</a>
                            {% endif %}
                            <a href='javascript:void(0);' class='info-link project-more-info'>More Info</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class='project-details row col-md-9 col-sm-9'>
                <div class='triangle-down'></div>
                <div class='project-long-info'>
                    {{ project.long_desc }}
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

urlshortener/templates/urlshortener/create_success.html
<h1>Success! You have created: {{ short_addr }}</h1>

<b>Original URL:</b> {{ long_url }}<br />
<b>Info Page:</b> <a href="{{ info_page }}">{{ info_page }}</a>
<br />
<br />
<b><a href="{% url 'short:index' %}">Return to index</a></b>

urlshortener/templates/urlshortener/index.html
{% extends 'urlshortener/short_base.html' %}

{%block body %}
<div class='content-container'>
    <div class="content">
    <div><div id="title">boff.io</div><div id="title-extension"></div></div>
    <form action="{% url 'short:create' %}" id="short_form" method="post">
        {% csrf_token %}
        <!--<label for="long_url">URL to shorten:</label>-->
        <input type="text" class="short_input" name="long_url" id="long_url" placeholder="URL to shorten" />
        <!--<label for="short_url">Short Name:</label>-->
        <input type="text" class="short_input" name="short_url" id="short_url" placeholder="Custom Name" />
        <input type="submit" value="Submit" id="short_submit" />
    </form>
</div>
{% endblock %}

urlshortener/templates/urlshortener/info.html
{% extends 'urlshortener/short_base.html' %}

{% block content-container %}
<h1>Info about Shortened URL: {{ short_addr }}</h1>

<b>Long URL:</b> {{ long_url }}<br />
<b>Views:</b> {{ views }}<br />
<b>Created:</b> {{ create_date }} (America/New_York)
{% endblock %}

urlshortener/templates/urlshortener/short_base.html
{% extends 'global_base.html' %}
{% load staticfiles %}

{% block more_header %}
<link rel="stylesheet" type="text/css" href="{% static 'urlshortener/css/short_app.css' %}" />
<script type="text/javascript" src="{% static 'urlshortener/js/main.js' %}"></script>
{% endblock %}

{% block title %}boff.io - The boffiest URL shortener{% endblock %}